config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get "tasks/new", to: "tasks#new"
  # Tenho que colocar o tasks/new antes de tasks/:id porque senão vai achar que new é
  # é um parâmetro, pois começam tem o mesmo VERB e ambos começam com tasks.
  post "tasks", to: "tasks#create"
  get 'tasks/:id', to: 'tasks#show', as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task # para ler o form
  patch "tasks/:id", to: "tasks#update" # enviar as respostas com o submit
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # Needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params) # params[:task] would raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # No need for app/views/tasks/destroy.html.erb
    redirect_to tasks_path, status: :see_other
    # status: :see_other responds with a 303 HTTP status code
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
    # Quando uso o form_for, ele já vem com o authenticity token. Então preciso só fazer:
    # params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.number_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task.id) %></li>
    <%# o (task) me mostra a instance de onde vai pegar o id e aí vai chegar até o path %>
  <% end %>
</ul>
<%= link_to "Create a new task!", tasks_new_path %></li>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.number_field :completed %>
  <%= f.submit %>
<% end %>
<%= link_to "See all tasks", tasks_path %></li>
<%# Quando uso o form_for, ele já vem com o authenticity token. Então preciso só fazer
os  params.require(:task).permit(:title, :details, :completed) %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>
<%= link_to "Edit task", edit_task_path(@task.id) %></li>
<%= link_to "See all tasks", tasks_path %></li>
<%= link_to "Delete",
  task_path(@task.id),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>